# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=5, null=True)),
                ('keyword', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
