# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0003_auto_20180702_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=5, null=True)),
                ('keyword', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
