# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0004_news_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_links',
            name='news_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
