# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_news_links_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_links',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
