# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0006_news_links_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searched_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('images_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('image_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Searched_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('news_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('news_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Searched_videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('videos_link', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField()),
                ('video_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
