# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0007_searched_images_searched_news_searched_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_username', models.CharField(blank=True, max_length=20, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
