# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-06 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0009_delete_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ss_username', models.CharField(max_length=20)),
                ('ss_client_id', models.CharField(max_length=50)),
                ('ss_client_secret', models.CharField(max_length=200)),
            ],
        ),
    ]
