# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0010_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access_token',
            name='ss_client_secret',
            field=models.CharField(max_length=300),
        ),
    ]
