# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-28 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0011_auto_20180808_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ky', models.CharField(blank=True, max_length=20, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Searched_videos')),
            ],
        ),
    ]
