# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0012_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_links',
            name='image_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='news_links',
            name='news_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='youtube_links',
            name='video_id',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
