# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0014_auto_20180915_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=5)),
                ('upload', models.FileField(upload_to=b'')),
                ('keys', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('file_access_mode', models.CharField(max_length=8)),
                ('file_type', models.CharField(max_length=8)),
            ],
        ),
    ]
