# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 12:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cmsapp', '0018_auto_20181011_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_GC_Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
                ('group_created_date', models.DateTimeField()),
                ('group_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='my_gc_group',
            name='tagged_by',
        ),
        migrations.DeleteModel(
            name='My_gc_group',
        ),
    ]
