# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0020_group_users_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group_users_list',
            name='gc_groups',
        ),
        migrations.AddField(
            model_name='group_users_list',
            name='group_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
