# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0022_auto_20181024_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywords',
            name='uploaded',
        ),
        migrations.AddField(
            model_name='keywords',
            name='upload_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
