# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0025_rest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='group_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
