# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-22 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0026_auto_20181119_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_uploaded_by', models.CharField(max_length=50)),
                ('camp_folder', models.CharField(max_length=50)),
                ('camp_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
    ]
