# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0028_campaign_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_campaign_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50)),
                ('text_file', models.FileField(blank=True, null=True, upload_to='campaigns/single_region')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='campaigns/single_region')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='campaigns'),
        ),
    ]
