# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0029_auto_20181126_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='single_campaign_upload',
            name='campaign_uploaded_by',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
