# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0031_multiple_campaign_files_multiple_campaign_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/multiple_region'),
        ),
    ]
