# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0032_multiple_campaign_upload_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_campaign_files',
            name='mul_files',
            field=models.FileField(upload_to='campaigns/'),
        ),
        migrations.AlterField(
            model_name='multiple_campaign_upload',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/'),
        ),
    ]
