# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0033_auto_20181129_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_campaign_upload',
            name='text_file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
