# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0034_auto_20181205_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_campaign_files',
            name='mul_files',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
