# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0036_auto_20181205_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_unique_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('user_unique_key', models.CharField(max_length=50)),
            ],
        ),
    ]
