# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-14 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0037_user_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
