# Generated by Django 2.0.9 on 2019-01-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0039_auto_20190105_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='is_skip',
            field=models.SmallIntegerField(default=0),
        ),
    ]
