# Generated by Django 2.0.9 on 2019-01-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0040_multiple_campaign_upload_is_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='camp_type',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
