# Generated by Django 2.0.9 on 2019-01-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0041_multiple_campaign_upload_camp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='stor_location',
            field=models.SmallIntegerField(default=1),
        ),
    ]
