# Generated by Django 2.0.9 on 2019-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0042_multiple_campaign_upload_stor_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_campaign_upload',
            name='campaign_uploaded_by',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
