# Generated by Django 2.0.9 on 2019-01-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0043_auto_20190128_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_campaign_upload',
            name='campaign_uploaded_by',
            field=models.BigIntegerField(),
        ),
    ]
