# Generated by Django 2.0.9 on 2019-01-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0044_auto_20190128_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='multiple_campaign_upload',
            unique_together={('campaign_uploaded_by', 'campaign_name')},
        ),
    ]
