# Generated by Django 2.0.9 on 2019-01-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0045_auto_20190128_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiple_campaign_upload',
            name='campaign_size',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
