# Generated by Django 2.0.9 on 2019-01-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple_campaign_upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_uploaded_by', models.CharField(max_length=10)),
                ('campaign_name', models.CharField(max_length=50)),
                ('text_file', models.FileField(blank=True, null=True, upload_to='campaigns/')),
                ('created_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField()),
                ('is_skip', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
