# Generated by Django 2.0.9 on 2019-01-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_multiple_campaign_upload_camp_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Multiple_campaign_upload',
        ),
    ]
