# Generated by Django 2.0.9 on 2019-01-28 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0042_multiple_campaign_upload_stor_location'),
        ('campaign', '0004_campaign_info'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='campaign_info',
            new_name='CampaignInfo',
        ),
    ]
