# Generated by Django 2.0.9 on 2019-01-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20190128_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigninfo',
            name='campaign_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmsapp.Multiple_campaign_upload', unique=True),
        ),
    ]
